#!/bin/bash
if [ -z "$1" ]
then
 	BRANCH=develop
	git push
 else
 	BRANCH=$1
 fi
 echo Deploying $BRANCH
ssh -tt imestav@185.93.71.214 <<EOF
 cd sapiyon/admin
 git checkout $BRANCH
 git pull
 yarn build
 rm -rf html
 mv build html
 exit
EOF
